### ISSUE TITLE
Simple CLI to test TES API, similar to Funnel

### ISSUE THREAD

**Issue by erikvdbergh** [elixir-cloud-aai/TESK#22]
Should support:
- `tesk get task [ID]  [--view MINIMAL/BASIC/FULL]` - No ID means all
- `tesk create task hello.json`
- `tesk run 'md5sum $src' --in src=~/src.txt` - by default, commands are wrapped in "sh -c" and run in the "alpine"* container.
- `tesk cancel ID`

Upon create / run the raw TES request should be shown.

**Comment by psafont** [comment]
Since tesk only knows about tasks, it could be simplified to

`tesk show $id [--view=minimal|basic|full / -v minimal|basic|full]`
`tesk build task.json`
`tesk cancel $id`

About the run command I think it's good to have a standardized way to run simple tasks, I have no idea on how to deal with those inputs/variables to read them. Hopefully it's easy enough to do it :)
